// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: web_referee_api/web_referee.proto

package web_referee_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebRefereeService_HealthCheck_FullMethodName = "/web.referee.service.v1.WebRefereeService/HealthCheck"
)

// WebRefereeServiceClient is the client API for WebRefereeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebRefereeServiceClient interface {
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type webRefereeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebRefereeServiceClient(cc grpc.ClientConnInterface) WebRefereeServiceClient {
	return &webRefereeServiceClient{cc}
}

func (c *webRefereeServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, WebRefereeService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebRefereeServiceServer is the server API for WebRefereeService service.
// All implementations must embed UnimplementedWebRefereeServiceServer
// for forward compatibility.
type WebRefereeServiceServer interface {
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedWebRefereeServiceServer()
}

// UnimplementedWebRefereeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebRefereeServiceServer struct{}

func (UnimplementedWebRefereeServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedWebRefereeServiceServer) mustEmbedUnimplementedWebRefereeServiceServer() {}
func (UnimplementedWebRefereeServiceServer) testEmbeddedByValue()                           {}

// UnsafeWebRefereeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebRefereeServiceServer will
// result in compilation errors.
type UnsafeWebRefereeServiceServer interface {
	mustEmbedUnimplementedWebRefereeServiceServer()
}

func RegisterWebRefereeServiceServer(s grpc.ServiceRegistrar, srv WebRefereeServiceServer) {
	// If the following call panics, it indicates UnimplementedWebRefereeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebRefereeService_ServiceDesc, srv)
}

func _WebRefereeService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebRefereeServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebRefereeService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebRefereeServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebRefereeService_ServiceDesc is the grpc.ServiceDesc for WebRefereeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebRefereeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "web.referee.service.v1.WebRefereeService",
	HandlerType: (*WebRefereeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _WebRefereeService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "web_referee_api/web_referee.proto",
}
