// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: models/models.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_models_models_proto protoreflect.FileDescriptor

const file_models_models_proto_rawDesc = "" +
	"\n" +
	"\x13models/models.proto\x12\x12students.models.v1B7Z5github.com/tengenatari/web-referee/internal/pb/modelsb\x06proto3"

var file_models_models_proto_goTypes = []any{}
var file_models_models_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_models_proto_init() }
func file_models_models_proto_init() {
	if File_models_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_models_proto_rawDesc), len(file_models_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_models_proto_goTypes,
		DependencyIndexes: file_models_models_proto_depIdxs,
	}.Build()
	File_models_models_proto = out.File
	file_models_models_proto_goTypes = nil
	file_models_models_proto_depIdxs = nil
}
