// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/tengenatari/web-referee/internal/models"
)

// WebRefereeProducer is an autogenerated mock type for the WebRefereeProducer type
type WebRefereeProducer struct {
	mock.Mock
}

// ProduceUser provides a mock function with given fields: ctx, user
func (_m *WebRefereeProducer) ProduceUser(ctx context.Context, user models.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for ProduceUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWebRefereeProducer creates a new instance of WebRefereeProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebRefereeProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebRefereeProducer {
	mock := &WebRefereeProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
