// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/tengenatari/web-referee/internal/models"

	uuid "github.com/google/uuid"
)

// WebRefereeStorage is an autogenerated mock type for the WebRefereeStorage type
type WebRefereeStorage struct {
	mock.Mock
}

// CreatePlayer provides a mock function with given fields: ctx, player
func (_m *WebRefereeStorage) CreatePlayer(ctx context.Context, player *models.Player) error {
	ret := _m.Called(ctx, player)

	if len(ret) == 0 {
		panic("no return value specified for CreatePlayer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Player) error); ok {
		r0 = rf(ctx, player)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTournament provides a mock function with given fields: ctx, tournament
func (_m *WebRefereeStorage) CreateTournament(ctx context.Context, tournament *models.Tournament) error {
	ret := _m.Called(ctx, tournament)

	if len(ret) == 0 {
		panic("no return value specified for CreateTournament")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Tournament) error); ok {
		r0 = rf(ctx, tournament)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *WebRefereeStorage) CreateUser(ctx context.Context, user *models.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPlayersByTournamentId provides a mock function with given fields: ctx, tournamentId
func (_m *WebRefereeStorage) GetPlayersByTournamentId(ctx context.Context, tournamentId uuid.UUID) ([]*models.Player, error) {
	ret := _m.Called(ctx, tournamentId)

	if len(ret) == 0 {
		panic("no return value specified for GetPlayersByTournamentId")
	}

	var r0 []*models.Player
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*models.Player, error)); ok {
		return rf(ctx, tournamentId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*models.Player); ok {
		r0 = rf(ctx, tournamentId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Player)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tournamentId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWebRefereeStorage creates a new instance of WebRefereeStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebRefereeStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebRefereeStorage {
	mock := &WebRefereeStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
